// Complete French Legal Structures - All forms with realistic tax/social implications

export type LegalStructureType = 
  // Individual structures
  | 'auto_entrepreneur'      // Micro-entrepreneur
  | 'ei'                     // Entreprise Individuelle
  | 'eirl'                   // EIRL (obsolete since 2022, kept for legacy)
  
  // Commercial companies
  | 'eurl'                   // EURL - SARL unipersonnelle
  | 'sarl'                   // SARL
  | 'sarl_famille'           // SARL de famille
  | 'sas'                    // SAS
  | 'sasu'                   // SASU - SAS unipersonnelle
  | 'sa'                     // Société Anonyme
  | 'snc'                    // Société en Nom Collectif
  | 'scs'                    // Société en Commandite Simple
  | 'sca'                    // Société en Commandite par Actions
  | 'sel'                    // Société d'Exercice Libéral
  | 'selarl'                 // SELARL
  | 'selas'                  // SELAS
  
  // Social economy
  | 'scop'                   // Société Coopérative
  | 'scic'                   // Société Coopérative d'Intérêt Collectif
  | 'association'            // Association loi 1901
  | 'association_rip'        // Association Reconnue d'Intérêt Public
  | 'fondation'              // Fondation
  | 'mutuelle'               // Mutuelle
  | 'gie'                    // Groupement d'Intérêt Économique
  | 'geie'                   // GEIE européen
  
  // Civil companies
  | 'sci'                    // Société Civile Immobilière
  | 'scm'                    // Société Civile de Moyens
  | 'scp'                    // Société Civile Professionnelle
  
  // Special forms
  | 'holding'                // Société Holding
  | 'se'                     // Société Européenne
  | 'sne';                   // Société de Nationalisation

export type TaxRegime = 
  | 'micro_bic'              // Micro-BIC (artisans/commerçants)
  | 'micro_bnc'              // Micro-BNC (professions libérales)
  | 'reel_simplifie'         // Réel simplifié
  | 'reel_normal'            // Réel normal
  | 'is'                     // Impôt sur les sociétés
  | 'ir_option'              // IR sur option
  | 'exonere';               // Exonéré (associations, etc.)

export type SocialRegime = 
  | 'tns'                    // Travailleur Non Salarié
  | 'tns_pamc'               // TNS + PAMC (médecins)
  | 'assimile_salarie'       // Assimilé salarié
  | 'regime_general'         // Régime général
  | 'non_applicable';        // Non applicable

export type TVARegime = 
  | 'franchise'              // Franchise en base (exo TVA)
  | 'reel_simplifie'         // Réel simplifié
  | 'reel_normal'            // Réel normal
  | 'exonere';               // Exonéré

export interface LegalStructure {
  id: LegalStructureType;
  name: string;
  fullName: string;
  description: string;
  category: 'individual' | 'commercial' | 'civil' | 'social' | 'special';
  
  // Capital requirements
  capitalMin: number;
  capitalMax: number | null;
  capitalRecommended: number;
  capitalLocked: boolean;
  
  // Associates
  associatesMin: number;
  associatesMax: number | null;
  
  // Employee limits
  employeesMax: number | null;
  
  // Revenue thresholds
  revenueThresholds: {
    micro?: number;          // Threshold for micro regime
    simplified?: number;     // Threshold for simplified regime
    max?: number;            // Max revenue allowed
  };
  
  // Tax configuration
  taxRegime: TaxRegime;
  taxRegimeOptions: TaxRegime[];
  corporateTaxRate: number;
  dividendTaxRate: number;
  
  // Social charges
  socialRegime: SocialRegime;
  socialChargesRate: number;
  socialChargesMin: number;
  
  // TVA
  tvaRegime: TVARegime;
  tvaThreshold: number;
  
  // Governance
  governanceComplexity: 1 | 2 | 3 | 4 | 5;
  requiresStatutes: boolean;
  requiresCommissaire: boolean;
  requiresCAC: boolean;
  requiresBoard: boolean;
  
  // Registration & costs
  registrationCost: number;
  annualCost: number;
  
  // Credibility & image
  credibilityBonus: number;
  institutionalImage: number;
  
  // Flexibility
  flexibilityScore: number;
  canRaiseFunds: boolean;
  canGoPublic: boolean;
  canExport: boolean;
  canHireAbroad: boolean;
  
  // Liability
  limitedLiability: boolean;
  personalGuaranteeRequired: boolean;
  
  // Specific obligations
  obligations: string[];
  advantages: string[];
  disadvantages: string[];
}

export const LEGAL_STRUCTURES: Record<LegalStructureType, LegalStructure> = {
  // ==================== INDIVIDUAL STRUCTURES ====================
  auto_entrepreneur: {
    id: 'auto_entrepreneur',
    name: 'Auto-Entrepreneur',
    fullName: 'Micro-Entrepreneur (Auto-Entrepreneur)',
    description: 'Statut simplifié pour activité individuelle avec plafonds de CA',
    category: 'individual',
    capitalMin: 0,
    capitalMax: null,
    capitalRecommended: 0,
    capitalLocked: false,
    associatesMin: 1,
    associatesMax: 1,
    employeesMax: 0,
    revenueThresholds: {
      micro: 77700,
      max: 188700,
    },
    taxRegime: 'micro_bic',
    taxRegimeOptions: ['micro_bic', 'micro_bnc'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'tns',
    socialChargesRate: 0.22,
    socialChargesMin: 0,
    tvaRegime: 'franchise',
    tvaThreshold: 36800,
    governanceComplexity: 1,
    requiresStatutes: false,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 0,
    annualCost: 100,
    credibilityBonus: -15,
    institutionalImage: 10,
    flexibilityScore: 90,
    canRaiseFunds: false,
    canGoPublic: false,
    canExport: false,
    canHireAbroad: false,
    limitedLiability: false,
    personalGuaranteeRequired: true,
    obligations: [
      'Déclaration mensuelle/trimestrielle CA',
      'Tenue livre des recettes',
      'Registre des achats (commerce)',
    ],
    advantages: [
      'Création gratuite et instantanée',
      'Comptabilité ultra-simplifiée',
      'Charges proportionnelles au CA',
      'Pas de TVA sous seuil',
    ],
    disadvantages: [
      'Plafonds de CA limitants',
      'Pas de déduction des charges',
      'Image peu professionnelle',
      'Responsabilité illimitée',
    ],
  },

  ei: {
    id: 'ei',
    name: 'EI',
    fullName: 'Entreprise Individuelle',
    description: 'Entreprise sans personnalité morale, patrimoine séparé depuis 2022',
    category: 'individual',
    capitalMin: 0,
    capitalMax: null,
    capitalRecommended: 5000,
    capitalLocked: false,
    associatesMin: 1,
    associatesMax: 1,
    employeesMax: null,
    revenueThresholds: {
      simplified: 247000,
    },
    taxRegime: 'reel_simplifie',
    taxRegimeOptions: ['micro_bic', 'micro_bnc', 'reel_simplifie', 'reel_normal'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'tns',
    socialChargesRate: 0.45,
    socialChargesMin: 1200,
    tvaRegime: 'reel_simplifie',
    tvaThreshold: 36800,
    governanceComplexity: 1,
    requiresStatutes: false,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 0,
    annualCost: 300,
    credibilityBonus: -10,
    institutionalImage: 20,
    flexibilityScore: 85,
    canRaiseFunds: false,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: false,
    limitedLiability: true,
    personalGuaranteeRequired: true,
    obligations: [
      'Comptabilité réelle',
      'Déclaration IS/TVA/URSSAF',
      'Dépôt des comptes annuels',
    ],
    advantages: [
      'Création simple',
      'Patrimoine séparé depuis 2022',
      'Liberté de gestion totale',
      'Possibilité d\'embaucher',
    ],
    disadvantages: [
      'Charges sociales élevées',
      'Difficile de lever des fonds',
      'Pas de transmission facile',
    ],
  },

  eirl: {
    id: 'eirl',
    name: 'EIRL',
    fullName: 'Entreprise Individuelle à Responsabilité Limitée',
    description: 'Statut obsolète depuis 2022, remplacé par EI',
    category: 'individual',
    capitalMin: 0,
    capitalMax: null,
    capitalRecommended: 5000,
    capitalLocked: false,
    associatesMin: 1,
    associatesMax: 1,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'reel_simplifie',
    taxRegimeOptions: ['reel_simplifie', 'reel_normal', 'is'],
    corporateTaxRate: 0.15,
    dividendTaxRate: 0.30,
    socialRegime: 'tns',
    socialChargesRate: 0.45,
    socialChargesMin: 1200,
    tvaRegime: 'reel_simplifie',
    tvaThreshold: 36800,
    governanceComplexity: 2,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 50,
    annualCost: 400,
    credibilityBonus: -5,
    institutionalImage: 25,
    flexibilityScore: 70,
    canRaiseFunds: false,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: false,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: ['Déclaration d\'affectation patrimoine', 'Comptes annuels'],
    advantages: ['Responsabilité limitée', 'Option IS possible'],
    disadvantages: ['Statut supprimé en 2022', 'Formalisme lourd'],
  },

  // ==================== COMMERCIAL COMPANIES ====================
  eurl: {
    id: 'eurl',
    name: 'EURL',
    fullName: 'Entreprise Unipersonnelle à Responsabilité Limitée',
    description: 'SARL avec un seul associé, responsabilité limitée aux apports',
    category: 'commercial',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 10000,
    capitalLocked: true,
    associatesMin: 1,
    associatesMax: 1,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is', 'ir_option'],
    corporateTaxRate: 0.15,
    dividendTaxRate: 0.30,
    socialRegime: 'tns',
    socialChargesRate: 0.45,
    socialChargesMin: 1200,
    tvaRegime: 'reel_simplifie',
    tvaThreshold: 0,
    governanceComplexity: 2,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 250,
    annualCost: 800,
    credibilityBonus: 5,
    institutionalImage: 40,
    flexibilityScore: 65,
    canRaiseFunds: true,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: [
      'Statuts écrits obligatoires',
      'Comptabilité complète',
      'Dépôt comptes au greffe',
      'Assemblée générale annuelle',
    ],
    advantages: [
      'Responsabilité limitée aux apports',
      'Crédibilité accrue',
      'Transmission facilitée',
      'Option IS ou IR',
    ],
    disadvantages: [
      'Formalisme juridique',
      'Coûts de création',
      'Charges sociales TNS',
    ],
  },

  sarl: {
    id: 'sarl',
    name: 'SARL',
    fullName: 'Société à Responsabilité Limitée',
    description: 'Forme classique des PME françaises, encadrement légal strict',
    category: 'commercial',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 15000,
    capitalLocked: true,
    associatesMin: 2,
    associatesMax: 100,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is', 'ir_option'],
    corporateTaxRate: 0.25,
    dividendTaxRate: 0.30,
    socialRegime: 'tns',
    socialChargesRate: 0.45,
    socialChargesMin: 1200,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 3,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 300,
    annualCost: 1200,
    credibilityBonus: 10,
    institutionalImage: 55,
    flexibilityScore: 50,
    canRaiseFunds: true,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: [
      'AG annuelle obligatoire',
      'Rapport de gestion',
      'Approbation des comptes',
      'Dépôt au greffe',
      'Registre des décisions',
    ],
    advantages: [
      'Responsabilité limitée',
      'Structure encadrée rassurante',
      'Protection du patrimoine personnel',
      'Cession de parts encadrée',
    ],
    disadvantages: [
      'Rigidité statutaire',
      'Cession de parts complexe',
      'Impossibilité d\'entrée en bourse',
    ],
  },

  sarl_famille: {
    id: 'sarl_famille',
    name: 'SARL Famille',
    fullName: 'SARL de Famille',
    description: 'SARL entre membres d\'une même famille avec régime fiscal spécial',
    category: 'commercial',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 10000,
    capitalLocked: true,
    associatesMin: 2,
    associatesMax: 100,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'ir_option',
    taxRegimeOptions: ['ir_option', 'is'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'tns',
    socialChargesRate: 0.45,
    socialChargesMin: 1200,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 3,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 300,
    annualCost: 1000,
    credibilityBonus: 8,
    institutionalImage: 45,
    flexibilityScore: 55,
    canRaiseFunds: false,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: ['Lien familial direct entre tous associés', 'Activité industrielle/commerciale/artisanale/agricole'],
    advantages: ['Imposition directe (pas d\'IS)', 'Transmission familiale facilitée', 'Déficits imputables'],
    disadvantages: ['Réservé aux familles', 'Responsabilité solidaire IR'],
  },

  sas: {
    id: 'sas',
    name: 'SAS',
    fullName: 'Société par Actions Simplifiée',
    description: 'Forme moderne très flexible, idéale pour startups et levées de fonds',
    category: 'commercial',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 50000,
    capitalLocked: true,
    associatesMin: 2,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is', 'ir_option'],
    corporateTaxRate: 0.25,
    dividendTaxRate: 0.30,
    socialRegime: 'assimile_salarie',
    socialChargesRate: 0.82,
    socialChargesMin: 0,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 3,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: true,
    requiresBoard: false,
    registrationCost: 400,
    annualCost: 1500,
    credibilityBonus: 20,
    institutionalImage: 75,
    flexibilityScore: 90,
    canRaiseFunds: true,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: [
      'Président obligatoire',
      'Comptes annuels et dépôt',
      'Registre des mouvements de titres',
      'CAC si seuils dépassés',
    ],
    advantages: [
      'Grande liberté statutaire',
      'Protection sociale président',
      'Attractif pour investisseurs',
      'Cession d\'actions libre',
      'BSPCE/BSA possibles',
    ],
    disadvantages: [
      'Charges sociales élevées',
      'Complexité de rédaction des statuts',
      'Coût de gestion',
    ],
  },

  sasu: {
    id: 'sasu',
    name: 'SASU',
    fullName: 'Société par Actions Simplifiée Unipersonnelle',
    description: 'SAS avec un seul associé, flexibilité maximale',
    category: 'commercial',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 30000,
    capitalLocked: true,
    associatesMin: 1,
    associatesMax: 1,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is', 'ir_option'],
    corporateTaxRate: 0.15,
    dividendTaxRate: 0.30,
    socialRegime: 'assimile_salarie',
    socialChargesRate: 0.82,
    socialChargesMin: 0,
    tvaRegime: 'reel_simplifie',
    tvaThreshold: 0,
    governanceComplexity: 2,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 350,
    annualCost: 1200,
    credibilityBonus: 15,
    institutionalImage: 65,
    flexibilityScore: 85,
    canRaiseFunds: true,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: ['Statuts', 'Comptes annuels', 'Décisions de l\'associé unique'],
    advantages: [
      'Flexibilité SAS + unicité',
      'Protection sociale',
      'Optimisation rémunération/dividendes',
      'Transformation facile en SAS',
    ],
    disadvantages: ['Charges sociales élevées si rémunération', 'Formalisme'],
  },

  sa: {
    id: 'sa',
    name: 'SA',
    fullName: 'Société Anonyme',
    description: 'Grande entreprise avec conseil d\'administration, peut être cotée',
    category: 'commercial',
    capitalMin: 37000,
    capitalMax: null,
    capitalRecommended: 500000,
    capitalLocked: true,
    associatesMin: 2,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is'],
    corporateTaxRate: 0.25,
    dividendTaxRate: 0.30,
    socialRegime: 'assimile_salarie',
    socialChargesRate: 0.82,
    socialChargesMin: 0,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 5,
    requiresStatutes: true,
    requiresCommissaire: true,
    requiresCAC: true,
    requiresBoard: true,
    registrationCost: 2000,
    annualCost: 10000,
    credibilityBonus: 40,
    institutionalImage: 95,
    flexibilityScore: 30,
    canRaiseFunds: true,
    canGoPublic: true,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: [
      'Conseil d\'administration (3-18 membres)',
      'Commissaire aux comptes obligatoire',
      'AG ordinaire et extraordinaire',
      'Rapport de gestion détaillé',
      'Publication BALO si cotée',
    ],
    advantages: [
      'Image prestigieuse',
      'Accès aux marchés financiers',
      'Structure de gouvernance claire',
      'Transmission par actions',
    ],
    disadvantages: [
      'Capital minimum élevé',
      'Formalisme très lourd',
      'Coûts de fonctionnement',
      'Procédures rigides',
    ],
  },

  snc: {
    id: 'snc',
    name: 'SNC',
    fullName: 'Société en Nom Collectif',
    description: 'Associés solidairement et indéfiniment responsables, transparence fiscale',
    category: 'commercial',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 20000,
    capitalLocked: false,
    associatesMin: 2,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'ir_option',
    taxRegimeOptions: ['ir_option', 'is'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'tns',
    socialChargesRate: 0.45,
    socialChargesMin: 1200,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 2,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 300,
    annualCost: 800,
    credibilityBonus: 5,
    institutionalImage: 35,
    flexibilityScore: 60,
    canRaiseFunds: false,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: false,
    personalGuaranteeRequired: true,
    obligations: ['Tous associés commerçants', 'Solidarité totale des dettes'],
    advantages: ['Transparence fiscale', 'Pas de capital minimum', 'Fonctionnement simple'],
    disadvantages: ['Responsabilité illimitée et solidaire', 'Cession parts unanimité'],
  },

  scs: {
    id: 'scs',
    name: 'SCS',
    fullName: 'Société en Commandite Simple',
    description: 'Commandités responsables, commanditaires limités aux apports',
    category: 'commercial',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 50000,
    capitalLocked: false,
    associatesMin: 2,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'ir_option',
    taxRegimeOptions: ['ir_option', 'is'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'tns',
    socialChargesRate: 0.45,
    socialChargesMin: 1200,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 3,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 400,
    annualCost: 1000,
    credibilityBonus: 8,
    institutionalImage: 40,
    flexibilityScore: 55,
    canRaiseFunds: true,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: false,
    personalGuaranteeRequired: true,
    obligations: ['Distinction commandités/commanditaires', 'Gérance par commandités'],
    advantages: ['Investisseurs passifs possibles', 'Flexibilité statuts'],
    disadvantages: ['Commandités responsables indéfiniment', 'Forme rare et méconnue'],
  },

  sca: {
    id: 'sca',
    name: 'SCA',
    fullName: 'Société en Commandite par Actions',
    description: 'Commandite avec capital divisé en actions, peut être cotée',
    category: 'commercial',
    capitalMin: 37000,
    capitalMax: null,
    capitalRecommended: 200000,
    capitalLocked: true,
    associatesMin: 4,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is'],
    corporateTaxRate: 0.25,
    dividendTaxRate: 0.30,
    socialRegime: 'tns',
    socialChargesRate: 0.45,
    socialChargesMin: 1200,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 5,
    requiresStatutes: true,
    requiresCommissaire: true,
    requiresCAC: true,
    requiresBoard: true,
    registrationCost: 2500,
    annualCost: 15000,
    credibilityBonus: 35,
    institutionalImage: 80,
    flexibilityScore: 40,
    canRaiseFunds: true,
    canGoPublic: true,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: false,
    personalGuaranteeRequired: true,
    obligations: ['Conseil de surveillance', 'Au moins 1 commandité gérant', '3 commanditaires minimum'],
    advantages: ['Protection contre OPA hostiles', 'Stabilité de la gérance', 'Cotation possible'],
    disadvantages: ['Très complexe', 'Commandités responsables', 'Forme rare'],
  },

  sel: {
    id: 'sel',
    name: 'SEL',
    fullName: 'Société d\'Exercice Libéral',
    description: 'Forme générique pour professions libérales réglementées',
    category: 'commercial',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 30000,
    capitalLocked: true,
    associatesMin: 1,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is', 'ir_option'],
    corporateTaxRate: 0.25,
    dividendTaxRate: 0.30,
    socialRegime: 'tns',
    socialChargesRate: 0.45,
    socialChargesMin: 1500,
    tvaRegime: 'exonere',
    tvaThreshold: 0,
    governanceComplexity: 3,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 500,
    annualCost: 1500,
    credibilityBonus: 25,
    institutionalImage: 70,
    flexibilityScore: 60,
    canRaiseFunds: true,
    canGoPublic: false,
    canExport: false,
    canHireAbroad: false,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: ['Agrément ordre professionnel', 'Majorité capital aux professionnels'],
    advantages: ['Exercice en société', 'Responsabilité limitée', 'Optimisation fiscale'],
    disadvantages: ['Réservé professions réglementées', 'Agrément obligatoire'],
  },

  selarl: {
    id: 'selarl',
    name: 'SELARL',
    fullName: 'Société d\'Exercice Libéral à Responsabilité Limitée',
    description: 'SEL sous forme de SARL pour professions libérales',
    category: 'commercial',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 20000,
    capitalLocked: true,
    associatesMin: 1,
    associatesMax: 100,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is', 'ir_option'],
    corporateTaxRate: 0.15,
    dividendTaxRate: 0.30,
    socialRegime: 'tns',
    socialChargesRate: 0.45,
    socialChargesMin: 1500,
    tvaRegime: 'exonere',
    tvaThreshold: 0,
    governanceComplexity: 3,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 400,
    annualCost: 1200,
    credibilityBonus: 20,
    institutionalImage: 65,
    flexibilityScore: 55,
    canRaiseFunds: false,
    canGoPublic: false,
    canExport: false,
    canHireAbroad: false,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: ['Agrément ordre', 'Règles SARL + profession'],
    advantages: ['Cadre SARL sécurisant', 'Taux IS réduit PME'],
    disadvantages: ['Moins flexible que SELAS'],
  },

  selas: {
    id: 'selas',
    name: 'SELAS',
    fullName: 'Société d\'Exercice Libéral par Actions Simplifiée',
    description: 'SEL sous forme de SAS pour professions libérales',
    category: 'commercial',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 50000,
    capitalLocked: true,
    associatesMin: 1,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is'],
    corporateTaxRate: 0.25,
    dividendTaxRate: 0.30,
    socialRegime: 'assimile_salarie',
    socialChargesRate: 0.82,
    socialChargesMin: 0,
    tvaRegime: 'exonere',
    tvaThreshold: 0,
    governanceComplexity: 3,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 500,
    annualCost: 1800,
    credibilityBonus: 28,
    institutionalImage: 75,
    flexibilityScore: 80,
    canRaiseFunds: true,
    canGoPublic: false,
    canExport: false,
    canHireAbroad: false,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: ['Agrément ordre', 'Règles SAS + profession'],
    advantages: ['Flexibilité SAS', 'Protection sociale', 'Entrée associés facilitée'],
    disadvantages: ['Charges sociales élevées'],
  },

  // ==================== SOCIAL ECONOMY ====================
  scop: {
    id: 'scop',
    name: 'SCOP',
    fullName: 'Société Coopérative et Participative',
    description: 'Entreprise détenue majoritairement par ses salariés',
    category: 'social',
    capitalMin: 30,
    capitalMax: null,
    capitalRecommended: 30000,
    capitalLocked: false,
    associatesMin: 2,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is'],
    corporateTaxRate: 0.25,
    dividendTaxRate: 0,
    socialRegime: 'regime_general',
    socialChargesRate: 0.45,
    socialChargesMin: 0,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 4,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 500,
    annualCost: 1500,
    credibilityBonus: 25,
    institutionalImage: 70,
    flexibilityScore: 50,
    canRaiseFunds: true,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: [
      'Salariés majoritaires au capital',
      '1 personne = 1 voix',
      'Réserves impartageables 16%+',
      'Révision coopérative',
    ],
    advantages: [
      'Exonération IS sur réserves',
      'Participation obligatoire avantageuse',
      'Engagement des salariés',
      'Image positive',
    ],
    disadvantages: [
      'Gouvernance complexe',
      'Difficile à revendre',
      'Réserves impartageables',
    ],
  },

  scic: {
    id: 'scic',
    name: 'SCIC',
    fullName: 'Société Coopérative d\'Intérêt Collectif',
    description: 'Coopérative multi-parties prenantes pour l\'intérêt général',
    category: 'social',
    capitalMin: 30,
    capitalMax: null,
    capitalRecommended: 50000,
    capitalLocked: false,
    associatesMin: 3,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is'],
    corporateTaxRate: 0.25,
    dividendTaxRate: 0,
    socialRegime: 'regime_general',
    socialChargesRate: 0.45,
    socialChargesMin: 0,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 5,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: true,
    registrationCost: 600,
    annualCost: 2000,
    credibilityBonus: 30,
    institutionalImage: 80,
    flexibilityScore: 40,
    canRaiseFunds: true,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: [
      '3 catégories d\'associés minimum',
      'Utilité sociale',
      'Agrément préfectoral',
      '57.5% minimum en réserves',
    ],
    advantages: [
      'Multi-parties prenantes',
      'Subventions possibles',
      'Image très positive',
      'Collectivités peuvent être associées',
    ],
    disadvantages: [
      'Gouvernance très complexe',
      'Agrément obligatoire',
      'Dividendes très limités',
    ],
  },

  association: {
    id: 'association',
    name: 'Association',
    fullName: 'Association Loi 1901',
    description: 'Groupement de personnes pour un but non lucratif',
    category: 'social',
    capitalMin: 0,
    capitalMax: null,
    capitalRecommended: 0,
    capitalLocked: false,
    associatesMin: 2,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'exonere',
    taxRegimeOptions: ['exonere', 'is'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'regime_general',
    socialChargesRate: 0.45,
    socialChargesMin: 0,
    tvaRegime: 'exonere',
    tvaThreshold: 0,
    governanceComplexity: 2,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 44,
    annualCost: 100,
    credibilityBonus: 15,
    institutionalImage: 60,
    flexibilityScore: 80,
    canRaiseFunds: true,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: [
      'But non lucratif',
      'Assemblée générale',
      'Tenue des comptes',
    ],
    advantages: [
      'Création quasi-gratuite',
      'Exonération fiscale (si non lucratif)',
      'Subventions/dons possibles',
      'Liberté de fonctionnement',
    ],
    disadvantages: [
      'Pas de distribution de bénéfices',
      'Crédibilité limitée pour affaires',
      'Ressources limitées',
    ],
  },

  association_rip: {
    id: 'association_rip',
    name: 'Association RIP',
    fullName: 'Association Reconnue d\'Intérêt Public',
    description: 'Association avec reconnaissance officielle, peut recevoir des legs',
    category: 'social',
    capitalMin: 0,
    capitalMax: null,
    capitalRecommended: 0,
    capitalLocked: false,
    associatesMin: 2,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'exonere',
    taxRegimeOptions: ['exonere'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'regime_general',
    socialChargesRate: 0.45,
    socialChargesMin: 0,
    tvaRegime: 'exonere',
    tvaThreshold: 0,
    governanceComplexity: 4,
    requiresStatutes: true,
    requiresCommissaire: true,
    requiresCAC: true,
    requiresBoard: true,
    registrationCost: 500,
    annualCost: 1000,
    credibilityBonus: 40,
    institutionalImage: 90,
    flexibilityScore: 40,
    canRaiseFunds: true,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: ['Décret en Conseil d\'État', 'Rapports financiers stricts', 'Contrôle préfectoral'],
    advantages: ['Peut recevoir legs et donations', 'Grande crédibilité', 'Avantages fiscaux donateurs'],
    disadvantages: ['Procédure très longue (3 ans+)', 'Contrôle strict', 'Fonctionnement encadré'],
  },

  fondation: {
    id: 'fondation',
    name: 'Fondation',
    fullName: 'Fondation d\'Utilité Publique',
    description: 'Affectation irrévocable de biens à une œuvre d\'intérêt général',
    category: 'social',
    capitalMin: 1500000,
    capitalMax: null,
    capitalRecommended: 2000000,
    capitalLocked: true,
    associatesMin: 1,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'exonere',
    taxRegimeOptions: ['exonere'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'regime_general',
    socialChargesRate: 0.45,
    socialChargesMin: 0,
    tvaRegime: 'exonere',
    tvaThreshold: 0,
    governanceComplexity: 5,
    requiresStatutes: true,
    requiresCommissaire: true,
    requiresCAC: true,
    requiresBoard: true,
    registrationCost: 10000,
    annualCost: 20000,
    credibilityBonus: 50,
    institutionalImage: 100,
    flexibilityScore: 20,
    canRaiseFunds: true,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: ['Décret Conseil d\'État', 'Dotation minimale 1.5M€', 'Conseil d\'administration', 'Contrôle annuel'],
    advantages: ['Prestige maximum', 'Pérennité', 'Avantages fiscaux importants'],
    disadvantages: ['Dotation très élevée', 'Procédure complexe', 'Irrévocable'],
  },

  mutuelle: {
    id: 'mutuelle',
    name: 'Mutuelle',
    fullName: 'Société Mutuelle',
    description: 'Organisme à but non lucratif pour la protection sociale',
    category: 'social',
    capitalMin: 0,
    capitalMax: null,
    capitalRecommended: 500000,
    capitalLocked: false,
    associatesMin: 500,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'exonere',
    taxRegimeOptions: ['exonere', 'is'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'regime_general',
    socialChargesRate: 0.45,
    socialChargesMin: 0,
    tvaRegime: 'exonere',
    tvaThreshold: 0,
    governanceComplexity: 5,
    requiresStatutes: true,
    requiresCommissaire: true,
    requiresCAC: true,
    requiresBoard: true,
    registrationCost: 5000,
    annualCost: 50000,
    credibilityBonus: 35,
    institutionalImage: 85,
    flexibilityScore: 25,
    canRaiseFunds: false,
    canGoPublic: false,
    canExport: false,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: ['Code de la mutualité', 'Agrément ACPR', 'Solvabilité II', 'Gouvernance stricte'],
    advantages: ['Pas de capital minimum', 'Exonération fiscale', 'Image solidaire'],
    disadvantages: ['Réglementation très stricte', 'Agrément complexe', 'Contrôle permanent'],
  },

  gie: {
    id: 'gie',
    name: 'GIE',
    fullName: 'Groupement d\'Intérêt Économique',
    description: 'Structure de coopération entre entreprises',
    category: 'social',
    capitalMin: 0,
    capitalMax: null,
    capitalRecommended: 10000,
    capitalLocked: false,
    associatesMin: 2,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'ir_option',
    taxRegimeOptions: ['ir_option', 'is'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'non_applicable',
    socialChargesRate: 0,
    socialChargesMin: 0,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 3,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 300,
    annualCost: 500,
    credibilityBonus: 10,
    institutionalImage: 50,
    flexibilityScore: 75,
    canRaiseFunds: false,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: false,
    personalGuaranteeRequired: true,
    obligations: ['Activité en prolongement des membres', 'Pas de bénéfices propres', 'Transparence fiscale'],
    advantages: ['Mutualisation de moyens', 'Flexibilité', 'Pas de capital minimum'],
    disadvantages: ['Responsabilité solidaire des membres', 'Activité limitée'],
  },

  geie: {
    id: 'geie',
    name: 'GEIE',
    fullName: 'Groupement Européen d\'Intérêt Économique',
    description: 'GIE à dimension européenne',
    category: 'social',
    capitalMin: 0,
    capitalMax: null,
    capitalRecommended: 50000,
    capitalLocked: false,
    associatesMin: 2,
    associatesMax: null,
    employeesMax: 500,
    revenueThresholds: {},
    taxRegime: 'ir_option',
    taxRegimeOptions: ['ir_option'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'non_applicable',
    socialChargesRate: 0,
    socialChargesMin: 0,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 4,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 1000,
    annualCost: 2000,
    credibilityBonus: 20,
    institutionalImage: 70,
    flexibilityScore: 60,
    canRaiseFunds: false,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: false,
    personalGuaranteeRequired: true,
    obligations: ['Au moins 2 membres de pays UE différents', 'Siège dans l\'UE', 'Max 500 salariés'],
    advantages: ['Coopération transfrontalière', 'Reconnaissance EU'],
    disadvantages: ['Responsabilité solidaire', 'Contraintes géographiques'],
  },

  // ==================== CIVIL COMPANIES ====================
  sci: {
    id: 'sci',
    name: 'SCI',
    fullName: 'Société Civile Immobilière',
    description: 'Gestion et transmission de patrimoine immobilier',
    category: 'civil',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 1000,
    capitalLocked: false,
    associatesMin: 2,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'ir_option',
    taxRegimeOptions: ['ir_option', 'is'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'non_applicable',
    socialChargesRate: 0,
    socialChargesMin: 0,
    tvaRegime: 'exonere',
    tvaThreshold: 0,
    governanceComplexity: 2,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 250,
    annualCost: 300,
    credibilityBonus: 5,
    institutionalImage: 40,
    flexibilityScore: 70,
    canRaiseFunds: false,
    canGoPublic: false,
    canExport: false,
    canHireAbroad: false,
    limitedLiability: false,
    personalGuaranteeRequired: true,
    obligations: ['Objet civil uniquement', 'Tenue comptable', 'AG annuelle'],
    advantages: ['Transmission facilitée', 'Gestion souple', 'Optimisation successorale'],
    disadvantages: ['Responsabilité illimitée', 'Pas d\'activité commerciale'],
  },

  scm: {
    id: 'scm',
    name: 'SCM',
    fullName: 'Société Civile de Moyens',
    description: 'Partage de moyens entre professionnels libéraux',
    category: 'civil',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 5000,
    capitalLocked: false,
    associatesMin: 2,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'ir_option',
    taxRegimeOptions: ['ir_option'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'non_applicable',
    socialChargesRate: 0,
    socialChargesMin: 0,
    tvaRegime: 'exonere',
    tvaThreshold: 0,
    governanceComplexity: 2,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 200,
    annualCost: 200,
    credibilityBonus: 5,
    institutionalImage: 35,
    flexibilityScore: 80,
    canRaiseFunds: false,
    canGoPublic: false,
    canExport: false,
    canHireAbroad: false,
    limitedLiability: false,
    personalGuaranteeRequired: true,
    obligations: ['Mise en commun de moyens uniquement', 'Pas d\'exercice en commun'],
    advantages: ['Mutualisation des coûts', 'Simplicité', 'Pas de TVA'],
    disadvantages: ['Responsabilité illimitée', 'Usage très spécifique'],
  },

  scp: {
    id: 'scp',
    name: 'SCP',
    fullName: 'Société Civile Professionnelle',
    description: 'Exercice en commun d\'une profession libérale réglementée',
    category: 'civil',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 20000,
    capitalLocked: false,
    associatesMin: 2,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'ir_option',
    taxRegimeOptions: ['ir_option', 'is'],
    corporateTaxRate: 0,
    dividendTaxRate: 0,
    socialRegime: 'tns',
    socialChargesRate: 0.45,
    socialChargesMin: 1500,
    tvaRegime: 'exonere',
    tvaThreshold: 0,
    governanceComplexity: 3,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 400,
    annualCost: 800,
    credibilityBonus: 15,
    institutionalImage: 55,
    flexibilityScore: 50,
    canRaiseFunds: false,
    canGoPublic: false,
    canExport: false,
    canHireAbroad: false,
    limitedLiability: false,
    personalGuaranteeRequired: true,
    obligations: ['Agrément ordre professionnel', 'Tous associés exercent'],
    advantages: ['Exercice en commun', 'Partage clientèle', 'Transmission facilitée'],
    disadvantages: ['Responsabilité solidaire', 'Réservé professions réglementées'],
  },

  // ==================== SPECIAL FORMS ====================
  holding: {
    id: 'holding',
    name: 'Holding',
    fullName: 'Société Holding',
    description: 'Société détenant des participations dans d\'autres sociétés',
    category: 'special',
    capitalMin: 1,
    capitalMax: null,
    capitalRecommended: 100000,
    capitalLocked: true,
    associatesMin: 1,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is'],
    corporateTaxRate: 0.05,
    dividendTaxRate: 0,
    socialRegime: 'assimile_salarie',
    socialChargesRate: 0.82,
    socialChargesMin: 0,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 4,
    requiresStatutes: true,
    requiresCommissaire: false,
    requiresCAC: false,
    requiresBoard: false,
    registrationCost: 500,
    annualCost: 3000,
    credibilityBonus: 30,
    institutionalImage: 80,
    flexibilityScore: 70,
    canRaiseFunds: true,
    canGoPublic: true,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: ['Gestion des participations', 'Régime mère-fille si éligible'],
    advantages: [
      'Régime mère-fille (exo 95% dividendes)',
      'Intégration fiscale possible',
      'LBO facilité',
      'Transmission optimisée',
    ],
    disadvantages: ['Animation nécessaire pour avantages', 'Complexité juridique'],
  },

  se: {
    id: 'se',
    name: 'SE',
    fullName: 'Société Européenne (Societas Europaea)',
    description: 'Forme juridique européenne pour opérations transfrontalières',
    category: 'special',
    capitalMin: 120000,
    capitalMax: null,
    capitalRecommended: 500000,
    capitalLocked: true,
    associatesMin: 2,
    associatesMax: null,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is'],
    corporateTaxRate: 0.25,
    dividendTaxRate: 0.30,
    socialRegime: 'assimile_salarie',
    socialChargesRate: 0.82,
    socialChargesMin: 0,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 5,
    requiresStatutes: true,
    requiresCommissaire: true,
    requiresCAC: true,
    requiresBoard: true,
    registrationCost: 5000,
    annualCost: 25000,
    credibilityBonus: 45,
    institutionalImage: 95,
    flexibilityScore: 50,
    canRaiseFunds: true,
    canGoPublic: true,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: ['Capital 120K€ minimum', 'Création par transformation/fusion/holding', 'Implication salariés'],
    advantages: ['Mobilité du siège dans l\'UE', 'Image européenne', 'Fusion transfrontalière facilitée'],
    disadvantages: ['Création complexe', 'Coûts élevés', 'Pas de création ex nihilo'],
  },

  sne: {
    id: 'sne',
    name: 'SNE',
    fullName: 'Société Nationalisée d\'État',
    description: 'Entreprise détenue par l\'État (ex: SNCF, EDF historique)',
    category: 'special',
    capitalMin: 0,
    capitalMax: null,
    capitalRecommended: 0,
    capitalLocked: true,
    associatesMin: 1,
    associatesMax: 1,
    employeesMax: null,
    revenueThresholds: {},
    taxRegime: 'is',
    taxRegimeOptions: ['is'],
    corporateTaxRate: 0.25,
    dividendTaxRate: 0,
    socialRegime: 'regime_general',
    socialChargesRate: 0.45,
    socialChargesMin: 0,
    tvaRegime: 'reel_normal',
    tvaThreshold: 0,
    governanceComplexity: 5,
    requiresStatutes: true,
    requiresCommissaire: true,
    requiresCAC: true,
    requiresBoard: true,
    registrationCost: 0,
    annualCost: 0,
    credibilityBonus: 50,
    institutionalImage: 100,
    flexibilityScore: 10,
    canRaiseFunds: true,
    canGoPublic: false,
    canExport: true,
    canHireAbroad: true,
    limitedLiability: true,
    personalGuaranteeRequired: false,
    obligations: ['Contrôle parlementaire', 'Cour des comptes', 'Missions de service public'],
    advantages: ['Garantie de l\'État', 'Accès financement illimité'],
    disadvantages: ['Non accessible aux privés', 'Contraintes politiques'],
  },
};

// Helper functions
export function getLegalStructure(id: LegalStructureType): LegalStructure {
  return LEGAL_STRUCTURES[id];
}

export function getLegalStructuresByCategory(category: LegalStructure['category']): LegalStructure[] {
  return Object.values(LEGAL_STRUCTURES).filter(s => s.category === category);
}

export function calculateRegistrationCosts(structure: LegalStructure, capital: number): number {
  let baseCost = structure.registrationCost;
  
  // Greffe fees based on capital
  if (capital > 225000) baseCost += 500;
  else if (capital > 100000) baseCost += 300;
  else if (capital > 50000) baseCost += 200;
  
  // Annonce légale
  baseCost += 150;
  
  return baseCost;
}

export function calculateAnnualObligations(structure: LegalStructure, revenue: number, employees: number): number {
  let cost = structure.annualCost;
  
  // CAC if required
  if (structure.requiresCAC) {
    cost += 3000;
    if (revenue > 1000000) cost += 2000;
    if (revenue > 5000000) cost += 5000;
  }
  
  // Dépôt des comptes
  if (structure.requiresCommissaire) {
    cost += 500;
  }
  
  // CSE if 11+ employees
  if (employees >= 11) {
    cost += employees * 50;
  }
  
  return cost;
}
